### ISSUE TITLE
[功能需求] docker镜像优化

### ISSUE THREAD

**Issue by Firfr** [setube/vue-xiuxiangame#78]
感谢开源的游戏项目，很好玩

我发现现在打包的docker镜像有300多兆，我优化了docker镜像的打包文件，让构建后的docker镜像只有12.3MB，可以大大提高体验，尤其国内可以大大提高镜像拉取速度，

下面是我的优化步骤

以下文件创建均在项目的根目录

## 创建docker构建忽略文件
减少镜像构建中不必要的文件复制
创建文件 `.dockerignore`
推荐内容
```
# git 配置
.git/
.github/

# 编辑器配置
.vscode/

# 依赖模块
node_modules/

# 编译文件
dist/

```

## 我优化后的镜像构建文件

```dockerfile
FROM node:20.19.0-alpine3.21 AS build
WORKDIR /app
COPY . .
RUN npm config set registry https://registry.npmmirror.com && \
    npm install && \
    npm run build

FROM svenstaro/miniserve:0.29.0-alpine AS runtime
# 设置端口
ENV MINISERVE_PORT=8080
WORKDIR /app
COPY --from=build /app/dist /app

EXPOSE 8080

CMD ["--index", "/app/index.html"]
```

## 部署命令

默认端口 8080，可通过设置环境变量`MINISERVE_PORT`的值来指定默认监听端口

### docker run 部署

```bash
docker run -d \
--name xiuxiangame \
--network bridge \
--restart always \
--log-opt max-size=1m \
--log-opt max-file=3 \
-p 8080:8080 \
setube/vue-xiuxiangame:latest
```

### compose文件部署

```yaml
#version: '3.9'
services:
  xiuxiangame:
    container_name: xiuxiangame
    image: setube/vue-xiuxiangame:latest
    network_mode: bridge
    restart: always
    # 限制容器产生的日志大写
    logging:
      options:
        max-size: 1m
        max-file: '3'
    ports:
      - 8080:8080
```
